version: "3.9"

services:
  backend:
    build: ./backend
    container_name: TNPortalBack
    ports:
      - "15610:5610"
    volumes:
      - ./backend/temp_audio_input:/app/temp_audio_input
    restart: always

  frontend:
    build: ./frontend
    container_name: TNPortalFront
    ports:
      - "18887:80"
    depends_on:
      - backend
